-- Only new immutable corrective suffixes are admitted; historical requests and native limits remain.
CREATE OR REPLACE FUNCTION public.videoforge_hosted_prompt_content_repair_matches(original jsonb, replacement jsonb)
RETURNS boolean LANGUAGE sql IMMUTABLE SET search_path=public,pg_catalog AS $$
  SELECT coalesce((original-'taskUUID'=replacement-'taskUUID') OR (
    jsonb_typeof(original->'settings')='object' AND jsonb_typeof(replacement->'settings')='object'
    AND jsonb_typeof(original#>'{settings,systemPrompt}')='string'
    AND replacement#>>'{settings,systemPrompt}'=ANY(ARRAY[
      (original#>>'{settings,systemPrompt}')||$v1$
MANDATORY NO GRAPHICS: Do not depict maps, sea charts, compass roses, graphs, diagrams, schematics, blueprints, drawn routes or marked paper in any required scene fact. These are forbidden even as physical props or historical navigation tools, even without readable words. For navigation or dead reckoning, show locally supported sailors, unmarked instruments, stars, ocean or shore instead. For abstract information, show its locally supported physical subject, process or consequence. Never invent writing, graphics or a substitute story event. Recheck literal_subject, action and environment before returning every scene; a forbidden prop rejects the entire batch.$v1$,
      (original#>>'{settings,systemPrompt}')||$v2$
MANDATORY NO GRAPHICS: Do not depict maps, sea charts, compass roses, graphs, diagrams, schematics, blueprints, drawn routes or marked paper in any required scene fact. These are forbidden even as physical props or historical navigation tools, even without readable words. For navigation or dead reckoning, show locally supported sailors, unmarked instruments, stars, ocean or shore instead. For abstract information, show its locally supported physical subject, process or consequence. Never invent writing, graphics or a substitute story event. Recheck literal_subject, action and environment before returning every scene; a forbidden prop rejects the entire batch.
NO TEXT-BEARING ACTIONS: This rule also applies when narration explicitly mentions writing, reading labels, prices, lists, calculations or documents. Show the locally supported physical person, items, interaction or observable consequence without text-bearing paper, product markings or depicted writing. For a narrated calculation, use the supported person considering the actual items; never a pen or pencil writing on paper, a notebook, a price list or a screen. For label comparisons, show supported unmarked containers and the person inspecting them without a label or invented portrait. Unmarked surfaces are valid; blank labels must be described as unmarked surfaces. Keep source people, setting and ordinary physical evidence. Do not invent a different event. In literal_subject, action and environment, remove all requests for written or drawn content before returning JSON.$v2$,
      CASE WHEN right(original#>>'{settings,systemPrompt}',length($v1$MANDATORY NO GRAPHICS: Do not depict maps, sea charts, compass roses, graphs, diagrams, schematics, blueprints, drawn routes or marked paper in any required scene fact. These are forbidden even as physical props or historical navigation tools, even without readable words. For navigation or dead reckoning, show locally supported sailors, unmarked instruments, stars, ocean or shore instead. For abstract information, show its locally supported physical subject, process or consequence. Never invent writing, graphics or a substitute story event. Recheck literal_subject, action and environment before returning every scene; a forbidden prop rejects the entire batch.$v1$))=$v1$MANDATORY NO GRAPHICS: Do not depict maps, sea charts, compass roses, graphs, diagrams, schematics, blueprints, drawn routes or marked paper in any required scene fact. These are forbidden even as physical props or historical navigation tools, even without readable words. For navigation or dead reckoning, show locally supported sailors, unmarked instruments, stars, ocean or shore instead. For abstract information, show its locally supported physical subject, process or consequence. Never invent writing, graphics or a substitute story event. Recheck literal_subject, action and environment before returning every scene; a forbidden prop rejects the entire batch.$v1$
        THEN (original#>>'{settings,systemPrompt}')||$v2$
NO TEXT-BEARING ACTIONS: This rule also applies when narration explicitly mentions writing, reading labels, prices, lists, calculations or documents. Show the locally supported physical person, items, interaction or observable consequence without text-bearing paper, product markings or depicted writing. For a narrated calculation, use the supported person considering the actual items; never a pen or pencil writing on paper, a notebook, a price list or a screen. For label comparisons, show supported unmarked containers and the person inspecting them without a label or invented portrait. Unmarked surfaces are valid; blank labels must be described as unmarked surfaces. Keep source people, setting and ordinary physical evidence. Do not invent a different event. In literal_subject, action and environment, remove all requests for written or drawn content before returning JSON.$v2$ END
    ])
    AND original-'taskUUID'=jsonb_set(replacement-'taskUUID','{settings,systemPrompt}',original#>'{settings,systemPrompt}')
  ),false);
$$;
REVOKE ALL ON FUNCTION public.videoforge_hosted_prompt_content_repair_matches(jsonb,jsonb) FROM PUBLIC;
