/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as StylesRouteImport } from './routes/styles'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as AvatarsRouteImport } from './routes/avatars'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StylesNewRouteImport } from './routes/styles/new'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as AvatarsNewRouteImport } from './routes/avatars/new'
import { Route as ProjectsProjectIdReviewRouteImport } from './routes/projects/$projectId/review'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesRoute = StylesRouteImport.update({
  id: '/styles',
  path: '/styles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarsRoute = AvatarsRouteImport.update({
  id: '/avatars',
  path: '/avatars',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesNewRoute = StylesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StylesRoute,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const AvatarsNewRoute = AvatarsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AvatarsRoute,
} as any)
const ProjectsProjectIdReviewRoute = ProjectsProjectIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avatars': typeof AvatarsRouteWithChildren
  '/library': typeof LibraryRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/styles': typeof StylesRouteWithChildren
  '/usage': typeof UsageRoute
  '/avatars/new': typeof AvatarsNewRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/styles/new': typeof StylesNewRoute
  '/projects/$projectId/review': typeof ProjectsProjectIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avatars': typeof AvatarsRouteWithChildren
  '/library': typeof LibraryRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/styles': typeof StylesRouteWithChildren
  '/usage': typeof UsageRoute
  '/avatars/new': typeof AvatarsNewRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/styles/new': typeof StylesNewRoute
  '/projects/$projectId/review': typeof ProjectsProjectIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avatars': typeof AvatarsRouteWithChildren
  '/library': typeof LibraryRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/styles': typeof StylesRouteWithChildren
  '/usage': typeof UsageRoute
  '/avatars/new': typeof AvatarsNewRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/styles/new': typeof StylesNewRoute
  '/projects/$projectId/review': typeof ProjectsProjectIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avatars'
    | '/library'
    | '/projects'
    | '/settings'
    | '/styles'
    | '/usage'
    | '/avatars/new'
    | '/projects/$projectId'
    | '/projects/new'
    | '/styles/new'
    | '/projects/$projectId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avatars'
    | '/library'
    | '/projects'
    | '/settings'
    | '/styles'
    | '/usage'
    | '/avatars/new'
    | '/projects/$projectId'
    | '/projects/new'
    | '/styles/new'
    | '/projects/$projectId/review'
  id:
    | '__root__'
    | '/'
    | '/avatars'
    | '/library'
    | '/projects'
    | '/settings'
    | '/styles'
    | '/usage'
    | '/avatars/new'
    | '/projects/$projectId'
    | '/projects/new'
    | '/styles/new'
    | '/projects/$projectId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvatarsRoute: typeof AvatarsRouteWithChildren
  LibraryRoute: typeof LibraryRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  StylesRoute: typeof StylesRouteWithChildren
  UsageRoute: typeof UsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styles': {
      id: '/styles'
      path: '/styles'
      fullPath: '/styles'
      preLoaderRoute: typeof StylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatars': {
      id: '/avatars'
      path: '/avatars'
      fullPath: '/avatars'
      preLoaderRoute: typeof AvatarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styles/new': {
      id: '/styles/new'
      path: '/new'
      fullPath: '/styles/new'
      preLoaderRoute: typeof StylesNewRouteImport
      parentRoute: typeof StylesRoute
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/avatars/new': {
      id: '/avatars/new'
      path: '/new'
      fullPath: '/avatars/new'
      preLoaderRoute: typeof AvatarsNewRouteImport
      parentRoute: typeof AvatarsRoute
    }
    '/projects/$projectId/review': {
      id: '/projects/$projectId/review'
      path: '/review'
      fullPath: '/projects/$projectId/review'
      preLoaderRoute: typeof ProjectsProjectIdReviewRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface AvatarsRouteChildren {
  AvatarsNewRoute: typeof AvatarsNewRoute
}

const AvatarsRouteChildren: AvatarsRouteChildren = {
  AvatarsNewRoute: AvatarsNewRoute,
}

const AvatarsRouteWithChildren =
  AvatarsRoute._addFileChildren(AvatarsRouteChildren)

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdReviewRoute: typeof ProjectsProjectIdReviewRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdReviewRoute: ProjectsProjectIdReviewRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface StylesRouteChildren {
  StylesNewRoute: typeof StylesNewRoute
}

const StylesRouteChildren: StylesRouteChildren = {
  StylesNewRoute: StylesNewRoute,
}

const StylesRouteWithChildren =
  StylesRoute._addFileChildren(StylesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvatarsRoute: AvatarsRouteWithChildren,
  LibraryRoute: LibraryRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  StylesRoute: StylesRouteWithChildren,
  UsageRoute: UsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
